server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: CHECKOUT-SERVICE
          uri: lb://CHECKOUT-SERVICE
          predicates:
            - Path=/api/v1/checkout/**
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**