server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: USER-SERIVCE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
#        - id: DEPARTMENT-SERVICE
#          uri: lb://DEPARTMENT-SERVICE
#          predicates:
#            - Path=/departments/**
