server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: USER-SERIVCE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
              - Path=/products/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - X-Requested-With
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE


